### ISSUE TITLE
Structure proposed

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dotkernel.github.io#1]
docs.dotkernel.org/api
docs.dotkernel.org/admin
docs.dotkernel.org/frotnend
docs.dotkernel.org/dot-mail
docs.dotkernel.org/dot-something

**Comment by arhimede** [comment]
or 
docs.dotkernel.org/libraries/dot-mail
docs.dotkernel.org/packages/dot-mail

**Comment by alexmerlin** [comment]
Already implemented.
