### ISSUE TITLE
upgrade favicon for docs.

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dotkernel.github.io#3]
https://github.com/dotkernel/dotkernel.github.io/blob/main/img/dk_docs_favicon_blue.svg
https://github.com/dotkernel/dotkernel.github.io/blob/main/img/dk_docs_favicon_white.svg

Please use one of those 2 favicons when you build the next time the docs 
probably the blue one on white bacground

**Comment by alexmerlin** [comment]
Here's a comparison between the two icons on both an active/inactive tab:
![image](https://github.com/dotkernel/dotkernel.github.io/assets/4542449/d98c2612-95fd-4944-b5c5-d170fc66aa5e)
![image](https://github.com/dotkernel/dotkernel.github.io/assets/4542449/612111ed-c855-46a2-a94c-bdf240df1507)
Let me know which one should I use.

**Comment by arhimede** [comment]
white logo on blue bck

**Comment by alexmerlin** [comment]
Fixed in #5 and https://github.com/dotkernel/dotkernel.github.io/commit/79fe3c1806959ceec5d6fb7cbe1eb66cc74edfba
