### ISSUE TITLE
increase font size to the main docs pages

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dotkernel.github.io#4]
example here:
https://docs.dotkernel.org/api/v4/introduction/introduction/

Plsase make the current font 18px,  which is currently 13px,

**Comment by alexmerlin** [comment]
Not sure which text you mean... both the paragraphs and list items are displayed using 16px fonts.
![image](https://github.com/dotkernel/dotkernel.github.io/assets/4542449/f35ddb60-18d9-4576-8b95-7cda6f32238d)
![image](https://github.com/dotkernel/dotkernel.github.io/assets/4542449/6e00d78f-617e-4fea-ae69-c0f1c6654aa1)

**Comment by arhimede** [comment]
nope, 13px 
try to make it 18px, there are anyway too small

**Comment by arhimede** [comment]
only in Edge are ok the fonts 
in firefox and chrome are too small

**Comment by alexmerlin** [comment]
Here's a comparison between `Firefox`/`Edge`/`Chrome` (in that order) on my external FHD display:
![image](https://github.com/dotkernel/dotkernel.github.io/assets/4542449/5a875bea-eef2-4ef4-afe2-55bbba96d26b)
I highlighted the same paragraph in each `Developer console`.
Not sure how it's rendered on a 4K display, though.

**Comment by alexmerlin** [comment]
Fixed in #5 and https://github.com/dotkernel/dotkernel.github.io/commit/79fe3c1806959ceec5d6fb7cbe1eb66cc74edfba
